### ISSUE TITLE
Can't delocate wheel with AttributeError after a regex returns no match in `parse_install_name`.

### ISSUE THREAD

**Issue by matham** [matthew-brett/delocate#78] opened 2020-06-27 17:04 UTC
I'm running delocate on [github actions](https://github.com/matham/ffpyplayer/runs/814320068?check_suite_focus=true) on a osx build and it errors out with the following error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/delocate-wheel", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/delocate/cmd/delocate_wheel.py", line 71, in main
    check_verbose=opts.verbose)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/delocate/delocating.py", line 377, in delocate_wheel
    lib_filt_func, copy_filt_func)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/delocate/delocating.py", line 289, in delocate_path
    return copy_recurse(lib_path, copy_filt_func, copied)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/delocate/delocating.py", line 145, in copy_recurse
    _copy_required(lib_path, copy_filt_func, copied_libs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/delocate/delocating.py", line 201, in _copy_required
    lib_dict = tree_libs(lib_path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/delocate/libsana.py", line 60, in tree_libs
    for install_name in get_install_names(depending_libpath):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/delocate/tools.py", line 219, in get_install_names
    names = tuple(parse_install_name(line)[0] for line in lines[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/delocate/tools.py", line 219, in <genexpr>
    names = tuple(parse_install_name(line)[0] for line in lines[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/delocate/tools.py", line 151, in parse_install_name
    return IN_RE.match(line).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

The command I'm running is `delocate-wheel dist/*.whl`, and the result of `ls dist/` prints `ffpyplayer-4.3.2.dev0-cp36-cp36m-macosx_10_9_x86_64.whl` indicating that the file is there.

**Comment by matthew-brett** [comment] 2020-06-27 17:05
Thanks for the report - is there any way you can provide me the input wheel, so I can try to reproduce?   Which xcode image are you using?

**Comment by matham** [comment] 2020-06-27 18:25
Here's the wheel under the [py_wheel_osx artifact](https://github.com/matham/ffpyplayer/actions/runs/149890573). I disabled the `delocate` part of the action so it would upload the originals so there's no error in this one, but the error occurred under python 3.6 (the first wheel compiled in the python versions).

I'm not sure about xcode. I'm not very familiar with osx. But it's using `macos-latest`, which is `macOS Catalina 10.15` accoriding to github. Here's the relevant part of the recipe:

```
osx_wheels:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Brew setup
        run: |
          brew update
          brew install pkg-config
          brew install sdl2
          brew install sdl2_mixer
          brew install ffmpeg
          pkg-config --libs --cflags libavcodec
      - name: Building wheels
        run: |
          mkdir ~/ffpyplayer_wheels

          for pyver in $OSX_PYVERS; do
             git reset --hard
             git clean -d -x -f
             pyver_short=${pyver:0:3}

             curl -O -L https://www.python.org/ftp/python/$pyver/python-$pyver-macosx10.9.pkg
             sudo installer -package python-$pyver-macosx10.9.pkg -target /
             curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
             python$pyver_short get-pip.py --user
             python$pyver_short -m pip install --upgrade --user pip
             python$pyver_short -m pip install --upgrade --user cython pytest wheel
             python$pyver_short -m pip install --upgrade delocate

             python$pyver_short setup.py bdist_wheel

             ls dist/
             cp dist/*.whl ~/ffpyplayer_wheels
          done
```

**Comment by matthew-brett** [comment] 2020-06-27 20:39
If you can, please try the code at #79 . I think it will fix this...

**Comment by matham** [comment] 2020-06-27 21:06
That indeed fixes it. Thanks for fixing it so quickly!

**Comment by papr** [comment] 2021-10-11 10:06
Hi, I am using `delocate==0.10.0` on `macOS 12.0 Beta 9` with Python 3.10 (installed via [`macOS 64-bit universal2 installer`](https://www.python.org/ftp/python/3.10.0/python-3.10.0-macos11.pkg)) and I am encountering the same issue as reported above:
```py
$ delocate-listdeps <name>-<version>-cp310-cp310-macosx_10_9_universal2.whl
Traceback (most recent call last):
  File ".../.venv/bin/delocate-listdeps", line 8, in <module>
    sys.exit(main())
  File ".../.venv/lib/python3.10/site-packages/delocate/cmd/delocate_listdeps.py", line 44, in main
    lib_dict = wheel_libs(path, ignore_missing=True)
  File ".../.venv/lib/python3.10/site-packages/delocate/libsana.py", line 731, in wheel_libs
    lib_dict = tree_libs_from_directory(
  File ".../.venv/lib/python3.10/site-packages/delocate/libsana.py", line 375, in tree_libs_from_directory
    return _tree_libs_from_libraries(
  File ".../.venv/lib/python3.10/site-packages/delocate/libsana.py", line 300, in _tree_libs_from_libraries
    for depending_path, install_name in get_dependencies(
  File ".../.venv/lib/python3.10/site-packages/delocate/libsana.py", line 100, in get_dependencies
    for install_name in get_install_names(lib_fname):
  File ".../.venv/lib/python3.10/site-packages/delocate/tools.py", line 246, in get_install_names
    names = tuple(parse_install_name(line)[0] for line in lines[1:])
  File ".../.venv/lib/python3.10/site-packages/delocate/tools.py", line 246, in <genexpr>
    names = tuple(parse_install_name(line)[0] for line in lines[1:])
  File ".../.venv/lib/python3.10/site-packages/delocate/tools.py", line 163, in parse_install_name
    return IN_RE.match(line).groups()
AttributeError: 'NoneType' object has no attribute 'groups'

$ xcode-select -p
/Library/Developer/CommandLineTools

$ otool --version
llvm-otool(1): Apple Inc. version cctools-986
otool(1): Apple Inc. version cctools-986
disassmbler: LLVM version 13.0.0, (clang-1300.0.29.3)
```

**Comment by HexDecimal** [comment] 2021-10-11 10:34
`parse_install_name` should really handle what happens when the match fails.

@papr, you should post your wheel if you can.

**Comment by papr** [comment] 2021-10-12 10:06
```py
❯ delocate-listdeps --version
delocate-listdeps 0.10.0+15.g8077870
❯ delocate-listdeps ndsi-1.4.2-cp310-cp310-macosx_10_9_universal2.whl
Traceback (most recent call last):
  File "/Users/ppr/work/pupil/.venv/bin/delocate-listdeps", line 8, in <module>
    sys.exit(main())
  File "/Users/ppr/work/pupil/.venv/lib/python3.10/site-packages/delocate/cmd/delocate_listdeps.py", line 55, in main
    lib_dict = wheel_libs(path, ignore_missing=True)
  File "/Users/ppr/work/pupil/.venv/lib/python3.10/site-packages/delocate/libsana.py", line 749, in wheel_libs
    lib_dict = tree_libs_from_directory(
  File "/Users/ppr/work/pupil/.venv/lib/python3.10/site-packages/delocate/libsana.py", line 384, in tree_libs_from_directory
    return _tree_libs_from_libraries(
  File "/Users/ppr/work/pupil/.venv/lib/python3.10/site-packages/delocate/libsana.py", line 309, in _tree_libs_from_libraries
    for depending_path, install_name in get_dependencies(
  File "/Users/ppr/work/pupil/.venv/lib/python3.10/site-packages/delocate/libsana.py", line 105, in get_dependencies
    for install_name in get_install_names(lib_fname):
  File "/Users/ppr/work/pupil/.venv/lib/python3.10/site-packages/delocate/tools.py", line 256, in get_install_names
    names = tuple(parse_install_name(line)[0] for line in lines[1:])
  File "/Users/ppr/work/pupil/.venv/lib/python3.10/site-packages/delocate/tools.py", line 256, in <genexpr>
    names = tuple(parse_install_name(line)[0] for line in lines[1:])
  File "/Users/ppr/work/pupil/.venv/lib/python3.10/site-packages/delocate/tools.py", line 170, in parse_install_name
    raise ValueError(f"Could not parse {line!r}")
ValueError: Could not parse '/private/var/folders/25/24p4_ynx17qf5p5ghpf9x7sr0000gn/T/tmpmnpne_qf/ndsi/writer.cpython-310-darwin.so (architecture arm64):'
```
```
❯ otool -L ndsi/writer.cpython-310-darwin.so
ndsi/writer.cpython-310-darwin.so (architecture x86_64):
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 905.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
ndsi/writer.cpython-310-darwin.so (architecture arm64):
	/opt/homebrew/opt/jpeg-turbo/lib/libturbojpeg.0.dylib (compatibility version 0.0.0, current version 0.2.0)
	/opt/homebrew/opt/ffmpeg/lib/libavutil.56.dylib (compatibility version 56.0.0, current version 56.70.100)
	/opt/homebrew/opt/ffmpeg/lib/libavformat.58.dylib (compatibility version 58.0.0, current version 58.76.100)
	/opt/homebrew/opt/ffmpeg/lib/libavcodec.58.dylib (compatibility version 58.0.0, current version 58.134.100)
	/opt/homebrew/opt/ffmpeg/lib/libswscale.5.dylib (compatibility version 5.0.0, current version 5.9.100)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 905.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
```

**Comment by papr** [comment] 2021-10-12 10:45
I did not figure out how to build a proper universal wheel yet... but once I do, I expect the `architecture x86_64` entries to point to the same file names but at different locations. The x86_64 homebrew uses a different prefix than the arm64 one.

As a result, delocating everything into `.dylibs/` might cause name clashes. Maybe it makes to delocate the entries for each architecture into a dedicated subfolder, i.e. `.dylibs/x86_64/` and `.dylibs/arm64/`?

**Comment by HexDecimal** [comment] 2021-10-13 19:49
I missed `delocate-fuse` and `lipo`.  Automatically merging architectures might be easier than I originally thought, but I'd hesitate to do that without knowing about the situations where `lipo` could fail or cause problems.

I think I have install name ids fixed in #130.  The changes in otool's output broke everything since it all was hard coded to expect only the one section instead of the possibility of a section per-architecture.  Luckily it's only parsed the 3 places and I've fixed two to them so far, thanks to papr showing the output since I don't have access to that myself.

The last one is the rpaths parser using `otool -l`.  I'd like @papr to show an example output again, and if you don't have libraries with rpaths then you can use [this wheel](https://github.com/matthew-brett/delocate/blob/master/delocate/tests/data/fakepkg_rpath-1.0-cp36-abi3-macosx_10_9_universal2.whl).

**Comment by papr** [comment] 2021-10-18 19:33
Apologies for the delayed response. Somehow this fall off my radar.

```py
Successfully installed delocate-0.10.0+19.g06a0fa8.dirty
❯ delocate-listdeps /Users/ppr/Downloads/fakepkg_rpath-1.0-cp36-abi3-macosx_10_9_universal2.whl

@rpath/libextfunc_rpath.dylib not found:
  Needed by: /private/var/folders/25/24p4_ynx17qf5p5ghpf9x7sr0000gn/T/tmp863r_gu1/fakepkg/subpkg/module2.abi3.so
  Search path:
    libs/

@rpath/libextfunc_rpath.dylib not found:
  Needed by: /private/var/folders/25/24p4_ynx17qf5p5ghpf9x7sr0000gn/T/tmp863r_gu1/fakepkg/subpkg/module2.abi3.so
  Search path:
    libs/
@rpath/libextfunc_rpath.dylib not found, requested by /private/var/folders/25/24p4_ynx17qf5p5ghpf9x7sr0000gn/T/tmp863r_gu1/fakepkg/subpkg/module2.abi3.so
```
```
❯ otool -l ~/Downloads/fakepkg_rpath-1.0-cp36-abi3-macosx_10_9_universal2/fakepkg/subpkg/module2.abi3.so | gh gist create
- Creating gist...
✓ Created gist
```
https://gist.github.com/5bdf5c7eff86698ffb63c5207855bc4e

**Comment by katringoogoo** [comment] 2021-12-29 20:04
hey whats the status of this? is there an update?

currently it still seems like the best solution is to not build universal binaries and build it separately :/

**Comment by HexDecimal** [comment] 2021-12-29 22:52
I have PR #130 but I wanted it to be reviewed before merging it.

You can use `pip install git+https://github.com/HexDecimal/delocate.git@fix-78` to test this PR yourself.

**Comment by katringoogoo** [comment] 2021-12-30 14:08
well it works in my case :) thx

**Closed** 2022-01-01 01:03 UTC
Labels: bug
